.TH gplaces 1
.SH NAME
gplaces - a Gemini client
.SH SYNOPSIS
.B gplaces
[-r rc-file] [url]
.SH DESCRIPTION
A simple terminal based Gemini client.
.SH COMMAND SYNTAX
.TP
.B HELP
.RS
Syntax:
.RS
HELP [<topic>]
.RE
Description:
.RS
Show all help topics or the help text for a specific <topic>.
.RE
.RE
.TP
.B SAVE
.RS
Syntax:
.RS
SAVE <item-id|url>
.RE
Description:
.RS
Saves the given <item-id> from the menu or a given <url> to the disk. You will be asked for a filename.
.RE
.RE
.TP
.B SEE
.RS
Syntax:
.RS
SEE <item-id>
.RE
Description:
.RS
Show the full Gemini URL for the menu selector id.
.RE
.RE
.TP
.B SET
.RS
Syntax:
.RS
SET [<name>] [<value>]
.RE
Description:
.RS
If no <name> is given it will show all variables. When <name> is given it will show this specific variable. If <data> is specified the variable will have this value. When the variable does not exist the variable will be created.
.RE
.RE
.TP
.B SHOW
.RS
Syntax:
.RS
SHOW [<filter>]
.RE
Description:
.RS
Show the current Gemini menu. If a <filter> is specified, it will show all selectors containing the <filter> in name or path.
.RE
.RE
.TP
.B SUBSCRIPTIONS
.RS
Syntax:
.RS
SUBSCRIPTIONS [<url>]
.RE
Description:
.RS
Subscribes to <url>. If no <url> is specified, it will show the list of subscriptions and the recent entries in each.
.RE
.RE
.SH FORMAT STRINGS
A format string can have the following formating options:
.RS
.IP
%% - simply a `%`
.IP
%s - scheme
.IP
%h - hostname
.IP
%p - port
.IP
%P - path
.IP
%r - human-readable string
.IP
%u - URL
.IP
%f - filename
.RE
.RE
.SH OPTIONS
.TP
.B -r
Specifies the initialization file to use. If unspecified, gplaces tries ~/.gplacesrc and /etc/gplacesrc.
.SH CONFIGURATION
.TP
.B mkcert
Specifies a client certificates generation command, as a format string. If unspecified or empty, automatic generation of client certificates is disabled.
.TP
.B pager
Specifies a pager used to display pages. If unspecified, the default is the value of the PAGER environment variable, if set, otherwise "less -r". If set to "cat", paging is disabled.
.TP
.B timeout
Specifies the download timeout. If unspecified or invalid, the default is 15 seconds.
.SH AUTHOR
.P
Dima Krasner (dima@dimakrasner.com)
.P
Sebastian Steinhauer <s.steinhauer@yahoo.de>
