.TH gplaces 1
.SH NAME
gplaces - a Gemini client
.SH SYNOPSIS
.B gplaces
[-r rc-file] [url]
.SH DESCRIPTION
A simple terminal based Gemini client.
.SH COMMAND SYNTAX
.TP
.B HELP
.RS
Syntax:
.RS
HELP [<topic>]
.RE
Description:
.RS
Show all help topics or the help text for a specific <topic>.
.RE
.RE
.TP
.B SAVE
.RS
Syntax:
.RS
SAVE <item-id|url> [<path>]
.RE
Description:
.RS
Saves the given <item-id> from the menu or a given <url> to the disk. If no filename is specified, you will be asked for it. If filename is "-", the downloaded data is streamed to the handler program via standard input.
.RE
.RE
.TP
.B SET
.RS
Syntax:
.RS
SET <name> <value>
.RE
Description:
.RS
Sets the value of a variable. When the variable does not exist the variable will be created.
.RE
.RE
.TP
.B SHOW
.RS
Syntax:
.RS
SHOW [<filter>]
.RE
Description:
.RS
Show the current Gemini menu. If a <filter> is specified, it will show all selectors containing the <filter> in name or path.
.RE
.RE
.TP
.B SUB
.RS
Syntax:
.RS
SUB [<url>]
.RE
Description:
.RS
Subscribes to <url>. If no <url> is specified, it will show the list of subscriptions and the recent entries in each.
.RE
.RE
.SH FORMAT STRINGS
A format string can have the following formating options:
.RS
.IP
%% - simply a `%`
.IP
%s - scheme
.IP
%h - hostname
.IP
%p - port
.IP
%P - path
.IP
%r - human-readable string
.IP
%u - URL
.IP
%f - filename
.RE
.RE
.SH OPTIONS
.TP
.B -r
Specifies the initialization file to use. If unspecified, gplaces tries $XDG_CONFIG_HOME/gplacesrc, ~/.gplacesrc and /etc/gplacesrc.
.SH CONFIGURATION
.TP
.B curve
Specifies the elliptic curve to use when generating client certificates. If unspecified or empty, the default is prime256v1.
.TP
.B digest
Specifies the message digest to use when generating client certificates. If unspecified or empty, the default is sha256.
.TP
.B cn
Specifies the Common Name to use when generating client certificates. If unspecified or empty, the default is the value of the USER environment variable.
.TP
.B days
Specifies the expiration of time of generated client certificates, in days. If unspecified or invalid, the default is 1825 days (5 years).
.TP
.B pager
Specifies a pager used to display pages. If unspecified, the default is the value of the PAGER environment variable, if set, otherwise "less -r". If set to "cat", paging is disabled.
.TP
.B timeout
Specifies the download timeout. If unspecified or invalid, the default is 15 seconds.
.TP
.B download_directory
Specifies the download directory. If unspecified or invalid, the default is the value of the XDG_DOWNLOAD_DIR environment variable, ~/Downloads or ~.
.SH AUTHOR
.P
Dima Krasner (dima@dimakrasner.com)
.P
Sebastian Steinhauer <s.steinhauer@yahoo.de>
